### ISSUE TITLE
NaN outputs

### ISSUE THREAD

**Issue by Krasner** [cstew2/asicp#2]
When running the test script or on my own data the output often is Nan:

Q
1 0 0
0 1 0
0 0 1
A
-nan(ind) -nan(ind) -nan(ind)
-nan(ind) -nan(ind) -nan(ind)
-nan(ind) -nan(ind) -nan(ind)
t
0
0
0

**Comment by cstew2** [comment]
This is still a work in progress, so I admit that it might not be working quite as intended. I just pushed some changes so you could try now(at least it won't spit out NaNs).
